# Copyright 2026 Noah Sherwin
# SPDX-License-Identifier: GPL-3.0-only

# ########
# Check if this file CMAKE_TOOLCHAIN_FILE or VCPKG_CHAINLOAD_TOOLCHAIN_FILE
# ########

# string(REGEX MATCH "((?:^|[\\/])toolchain_loader.cmake)" IS_TOOLCHAIN_LOADER_PREPPED "${CMAKE_TOOLCHAIN_FILE}|${VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
string(FIND "${CMAKE_TOOLCHAIN_FILE}|${VCPKG_CHAINLOAD_TOOLCHAIN_FILE}" "toolchain_loader.cmake" IS_TOOLCHAIN_LOADER_PREPPED)

if(NOT IS_TOOLCHAIN_LOADER_PREPPED)
  message(SEND_ERROR "This file should be loaded as a toolchain")
endif()

set(CMAKE_TOOLCHAIN_FILE_LIST "$ENV{CMAKE_TOOLCHAIN_FILE_LIST}")
list(LENGTH CMAKE_TOOLCHAIN_FILE_LIST CMAKE_TOOLCHAIN_FILE_LIST_LENGTH)
message(VERBOSE "  | BEFORE
  CMAKE_TOOLCHAIN_FILE_LIST_LENGTH: ${CMAKE_TOOLCHAIN_FILE_LIST_LENGTH}
  CMAKE_TOOLCHAIN_FILE_LIST: ${CMAKE_TOOLCHAIN_FILE_LIST}
  CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}
  VCPKG_OVERLAY_TRIPLETS: ${VCPKG_OVERLAY_TRIPLETS}
  VCPKG_TARGET_TRIPLET: ${VCPKG_TARGET_TRIPLET}
  VCPKG_TARGET_ARCHITECTURE: ${VCPKG_TARGET_ARCHITECTURE}")

# ########
# Chain-load additional toolchain files
# ########
foreach(TOOLCHAIN IN LISTS CMAKE_TOOLCHAIN_FILE_LIST)
  include("${TOOLCHAIN}")
  message(VERBOSE "  | AFTER
  TOOLCHAIN: ${TOOLCHAIN}
  CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}
  CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}
  CMAKE_SYSTEM_VERSION: ${CMAKE_SYSTEM_VERSION}
  CMAKE_CROSSCOMPILING: ${CMAKE_CROSSCOMPILING}
  TARGET: ${TARGET}
  CMAKE_C_COMPILER_TARGET: ${CMAKE_C_COMPILER_TARGET}
  CMAKE_CXX_COMPILER_TARGET: ${CMAKE_CXX_COMPILER_TARGET}
  TARGET_PREFIX: ${TARGET_PREFIX}
  CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}
  CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}
  CMAKE_RANLIB: ${CMAKE_RANLIB}
  CMAKE_RC_COMPILER: ${CMAKE_RC_COMPILER}
  CMAKE_AR: ${CMAKE_AR}
  CMAKE_FIND_ROOT_PATH: ${CMAKE_FIND_ROOT_PATH}
  CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS: ${CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS}
  VCPKG_LIBRARY_LINKAGE: ${VCPKG_LIBRARY_LINKAGE}")
endforeach()

# hacky overrides

# Windows 7; MSBuildCMake.SDK's MinGW32.cmake toolchain file sets this to Windows 10; we don't want that!
set(CMAKE_SYSTEM_VERSION 6.1)

# No matter what I try, VCPKG_TARGET_ARCHITECTURE is becoming undefined before it is read and converted to CMAKE_SYSTEM_PROCESSOR
# set(VCPKG_TARGET_ARCHITECTURE "x86"), set(CACHE{VCPKG_TARGET_ARCHITECTURE} VALUE "x86" FORCE), et cetera
# So, we try overriding CMAKE_SYSTEM_PROCESSOR here, instead.
if(NOT DEFINED CMAKE_SYSTEM_PROCESSOR)
  set(CACHE{CMAKE_SYSTEM_PROCESSOR} VALUE "x86")
endif()
# CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and CMAKE_RC_COMPILER are set by the triplet
set(CMAKE_C_FLAGS_INIT "-static-libgcc")
set(CMAKE_CXX_FLAGS_INIT "-static-libgcc -static-libstdc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libgcc -static-libstdc++")

# some triplets set this to 'dynamic'; we need 'static' lib-linking
set(VCPKG_LIBRARY_LINKAGE static)
