name: release

# TODO
# - Allow workflows to be driven by the project(s)

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
  release:
    name: Release
    # required for proper WPF builds/publishes
    runs-on: windows-latest
    needs: ci
    permissions:
      contents: write # publish a GitHub Release
      issues: write # comment on released issues
      packages: write # push packages to "HaloSPV3" GitHub Nuget Package Registry
      pull-requests: write # comment on released pull requests

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Required by GitVersion
          submodules: "recursive"

      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v7
      - run: corepack enable

      - run: yarn install
      # Dependents: Semantic Release

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      ################
      # BUILD
      ################
      - name: build solution
        run: |
          msbuild src /p:Configuration="Release"

      # required variables: GitVersion_FullSemVer
      - name: Compress-PublishArtifacts
        run: |
          $publishPath = Resolve-Path "./publish/";
          $archiveName = "$env:ASSEMBLYNAME.$env:GitVersion_FullSemVer.zip";
          Set-Location $publishPath;
          Compress-Archive -Path $publishPath -DestinationPath $archiveName -CompressionLevel Optimal;

      ################
      # RELEASE
      ################
      # https://github.com/marketplace/actions/action-for-semantic-release
      - name: Setup Semantic Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: publish-artifacts
          path: publish
